### ISSUE TITLE
'bind *:443' : unable to load SSL certificate from PEM file

### ISSUE THREAD

**Issue by git4suvendu** [voyagermesh/voyager#1454]
Deployed cert manager in namespace **cert-manager**.
Deployed Voyager in namespace **voyager-controller**

Why SSL certificate is not getting loaded in haproxy controller?

**Cluster Issuer:**
```

---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-issuer
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: suvendu.mandal@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: staging-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            name: fanout-ingress-voyager #Ingress name.
---
```

**Ingress Resource:**

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress-voyager
  namespace: xyz-product
  annotations:
    kubernetes.io/ingress.class: voyager
    cert-manager.io/cluster-issuer: "letsencrypt-staging-issuer"
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
        - apps.bauxite-viu.co.uk
      secretName: apps-bauxite-viu-tls
  rules:
    - http:
        paths:
        - path: /user-reg/create/*
          backend:
            serviceName: prod-user-reg-create-app
            servicePort: 8081
---
```

**Error from Ingress resource log**

```
  Normal   DeploymentReconcileSuccessful  9m9s  voyager-operator    Successfully created HAProxy Deployment voyager-fanout-ingress-voyager
  Normal   ServiceReconcileSuccessful     9m9s  voyager-operator    Successfully created LoadBalancer Service voyager-fanout-ingress-voyager
  Normal   CreateCertificate              9m9s  cert-manager        Successfully created Certificate "apps-bauxite-viu-tls"
  Warning  BackendInvalid                 9m7s  voyager-operator    can't resolve backend for spec.rules[1].http.paths[0], reason: endpoint not found
  Normal   ConfigMapReconcileSuccessful   9m7s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                 9m7s  haproxy-controller  haproxy-check failed, reason: [ALERT] 331/160926 (23) : parsing [/etc/haproxy/haproxy.cfg:52] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/160926 (23) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/160926 (23) : Fatal errors found in configuration.
 exit status 1
  Normal   DeploymentReconcileSuccessful  9m7s  voyager-operator    Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal   StatsServiceDeleteSuccessful   9m7s  voyager-operator    Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal   ServiceReconcileSuccessful     9m7s  voyager-operator    Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Normal   ConfigMapReconcileSuccessful   9m2s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                 9m2s  haproxy-controller  haproxy-check failed, reason: [ALERT] 331/160931 (24) : parsing [/etc/haproxy/haproxy.cfg:52] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/160931 (24) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/160931 (24) : Fatal errors found in configuration.
 exit status 1
  Warning  TLSMountFailed  9m2s  haproxy-controller  haproxy-check failed, reason: [ALERT] 331/160931 (28) : parsing [/etc/haproxy/haproxy.cfg:52] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/160931 (28) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/160931 (28) : Fatal errors found in configuration.
 exit status 1
  Normal  DeploymentReconcileSuccessful  9m2s  voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   9m2s  voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal  DeploymentReconcileSuccessful  40s   voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  ServiceReconcileSuccessful     40s   voyager-operator  Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   40s   voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal  DeploymentReconcileSuccessful  40s   voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  ServiceReconcileSuccessful     40s   voyager-operator  Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   40s   voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
```

**Comment by git4suvendu** [comment]
```
kubectl describe certificate apps-bauxite-viu-tls -n xyz-product

Name:         apps-bauxite-viu-tls
Namespace:    xyz-product
Labels:       <none>
Annotations:  <none>
API Version:  cert-manager.io/v1alpha2
Kind:         Certificate
Metadata:
  Creation Timestamp:  2019-11-28T16:09:24Z
  Generation:          1
  Owner References:
    API Version:           extensions/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Ingress
    Name:                  fanout-ingress-voyager
    UID:                   71e96ed0-11f9-11ea-a99b-42010a9a008d
  Resource Version:        85624
  Self Link:               /apis/cert-manager.io/v1alpha2/namespaces/xyz-product/certificates/apps-bauxite-viu-tls
  UID:                     71ec4207-11f9-11ea-a99b-42010a9a008d
Spec:
  Dns Names:
    apps.bauxite-viu.co.uk
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt-staging-issuer
  Secret Name:  apps-bauxite-viu-tls
Status:
  Conditions:
    Last Transition Time:  2019-11-28T16:09:24Z
    Message:               Waiting for CertificateRequest "apps-bauxite-viu-tls-345221582" to complete
    Reason:                InProgress
    Status:                False
    Type:                  Ready
Events:
  Type    Reason     Age   From          Message
  ----    ------     ----  ----          -------
  Normal  Requested  25m   cert-manager  Created new CertificateRequest resource "apps-bauxite-viu-tls-345221582"
```

**Comment by tamalsaha** [comment]
I believe the actual certificate does not exist inside `secretName: apps-bauxite-viu-tls`. Can you please confirm?

**Comment by git4suvendu** [comment]
@tamalsaha If you refer cluster Issuer YAML then the secret name is staging-issuer-account-key and it's in the cert-manager namespace.
secretName: apps-bauxite-viu-tls I have declared in Ingress YAML only.
Do I need to provide same secret name both in Cluster Issuer and Ingress Resource?

**Comment by tamalsaha** [comment]
Ingress yaml needs a secret that has tls.crt and tls.key entries. Otherwise, Voyager/HAPRoxy will not be able to start, since it can't find the certificate.

**Comment by git4suvendu** [comment]
@tamalsaha I am using Let's Encrypt to get the cert and key. There is a cert-manager in the cluster. Where do I get tls.crt and key?
I thought it would be automatically generated by cert-manager.

**Comment by git4suvendu** [comment]
In this example also "quickstart-kiteci-tls" has been declared. So the certificate and key will be automatically generated will be stored here, right? Or am I wrong?

https://appscode.com/products/voyager/v11.0.1/guides/cert-manager/http01_challenge/overview/

**Comment by git4suvendu** [comment]
@tamalsaha Any suggestion on how to resolve the issue? I am new here. so clueless now !!!

**Comment by tamalsaha** [comment]
You should create the ingress yaml with the tls part so that HAProxy can start.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress-voyager
  namespace: xyz-product
  annotations:
    kubernetes.io/ingress.class: voyager
    cert-manager.io/cluster-issuer: "letsencrypt-staging-issuer"
    cert-manager.io/acme-challenge-type: http01
spec:
  rules:
    - http:
        paths:
        - path: /user-reg/create/*
          backend:
            serviceName: prod-user-reg-create-app
            servicePort: 8081
```

Once the actual secret `secretName: apps-bauxite-viu-tls` has been created, you can add the spec.tls part to the Ingress to enable SSL serving.

**Comment by git4suvendu** [comment]
with the tls part or without the tls part?
If I create ingress without tls then how the actual secret  apps-bauxite-viu-tls will be created? Sorry bit confusing here.

**Comment by tamalsaha** [comment]
**without** the tls part.

**Comment by git4suvendu** [comment]
I have created the ingress without the tls and host part. It created a load balancer also. Then what? How do I enable tls now? What do you mean by "Once the actual secret secretName: apps-bauxite-viu-tls has been created"? 

```
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl describe ingress fanout-ingress-voyager -n xyz-product                                              
Name:             fanout-ingress-voyager
Namespace:        xyz-product
Address:
Default backend:  default-http-backend:80 (10.0.0.8:8080)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *
        /user-reg/create/*   prod-user-reg-create-app:8081 (<none>)
Annotations:
  cert-manager.io/acme-challenge-type:               http01
  cert-manager.io/cluster-issuer:                    letsencrypt-staging-issuer
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/acme-challenge-type":"http01","cert-manager.io/cluster-issuer":"letsencrypt-staging-issuer","kubernetes.io/ingress.class":"voyager"},"name":"fanout-ingress-voyager","namespace":"xyz-product"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"prod-user-reg-create-app","servicePort":8081},"path":"/user-reg/create/*"}]}}]}}

  kubernetes.io/ingress.class:  voyager
Events:
  Type    Reason                         Age   From              Message
  ----    ------                         ----  ----              -------
  Normal  ConfigMapReconcileSuccessful   37s   voyager-operator  Successfully created ConfigMap voyager-fanout-ingress-voyager
  Normal  RBACSuccessful                 37s   voyager-operator  Successfully created ServiceAccount voyager-fanout-ingress-voyager
  Normal  RBACSuccessful                 37s   voyager-operator  Successfully created Role voyager-fanout-ingress-voyager
  Normal  RBACSuccessful                 37s   voyager-operator  Successfully created RoleBinding voyager-fanout-ingress-voyager
  Normal  DeploymentReconcileSuccessful  37s   voyager-operator  Successfully created HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  ServiceReconcileSuccessful     37s   voyager-operator  Successfully created LoadBalancer Service voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   37s   voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
```

**Comment by tamalsaha** [comment]
Does `kubectl get secret apps-bauxite-viu-tls -n  xyz-product` show anything?

**Comment by git4suvendu** [comment]
yes. But how it has been created? Nowhere I have mentioned this secret? Even nowhere I have mentioned the name itself "apps-bauxite-viu-tls".

```
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl get secret apps-bauxite-viu-tls -n xyz-product
NAME                   TYPE                DATA   AGE
apps-bauxite-viu-tls   kubernetes.io/tls   3      144m
```

**Comment by tamalsaha** [comment]
It has been created by the cert-manager, because your ingress.yaml has the following annotations:

```
metadata:
  name: fanout-ingress-voyager
  namespace: xyz-product
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging-issuer"
    cert-manager.io/acme-challenge-type: http01
```

Now, you can edit the ingress yaml to add the spec.tls part. That should reconfigure HAProxy to serve https traffic.

**Comment by git4suvendu** [comment]
Ok but why only this name "apps-bauxite-viu-tls"? Why not any other name?

**Comment by git4suvendu** [comment]
Got the same issue which I was getting previously.

```
  Warning  BackendInvalid                 62s   voyager-operator    can't resolve backend for spec.rules[1].http.paths[0], reason: endpoint not found
  Normal   DeploymentReconcileSuccessful  61s   voyager-operator    Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                 61s   haproxy-controller  haproxy-check failed, reason: [ALERT] 331/181715 (30) : parsing [/etc/haproxy/haproxy.cfg:54] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/181715 (30) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/181715 (30) : Fatal errors found in configuration.
 exit status 1
  Normal   ServiceReconcileSuccessful    61s  voyager-operator    Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Normal   StatsServiceDeleteSuccessful  61s  voyager-operator    Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal   ConfigMapReconcileSuccessful  61s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Normal   StatsServiceDeleteSuccessful  60s  voyager-operator    Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal   ConfigMapReconcileSuccessful  60s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                60s  haproxy-controller  haproxy-check failed, reason: [ALERT] 331/181716 (31) : parsing [/etc/haproxy/haproxy.cfg:54] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/181716 (31) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/181716 (31) : Fatal errors found in configuration.
 exit status 1
  Normal  ServiceReconcileSuccessful     60s  voyager-operator  Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Normal  DeploymentReconcileSuccessful  60s  voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  DeploymentReconcileSuccessful  23s  voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   23s  voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal  DeploymentReconcileSuccessful  23s  voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  ServiceReconcileSuccessful     23s  voyager-operator  Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   23s  voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats

```

**Comment by tamalsaha** [comment]
> Ok but why only this name "apps-bauxite-viu-tls"? Why not any other name?

You can use any other name.

**Comment by tamalsaha** [comment]
` Warning  BackendInvalid                 62s   voyager-operator    can't resolve backend for spec.rules[1].http.paths[0], reason: endpoint not found
`

Do you have a service called `prod-user-reg-create-app` ?

`kubectl get svc prod-user-reg-create-app -n xyz-product`

**Comment by git4suvendu** [comment]
I have deleted the ingress and secret "apps-bauxite-viu-tls". Then deployed the ingress without the tls part. Guess what?? There is no secret created named "apps-bauxite-viu-tls".

```

imal-cogency-258718)$ kubectl get secret apps-bauxite-viu-tls -n xyz-product                                                      
NAME                   TYPE                DATA   AGE
apps-bauxite-viu-tls   kubernetes.io/tls   3      160m
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl delete secret apps-bauxite-viu-tls -n xyz-product
secret "apps-bauxite-viu-tls" deleted
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl apply -f fanout-ingress-voyager.yaml                                                                
ingress.extensions/fanout-ingress-voyager created
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ vi fanout-ingress-voyager.yaml
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl get secret apps-bauxite-viu-tls -n xyz-product
Error from server (NotFound): secrets "apps-bauxite-viu-tls" not found


ingress.extensions/fanout-ingress-voyager created
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ vi fanout-ingress-voyager.yaml
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl get secret apps-bauxite-viu-tls -n xyz-product
Error from server (NotFound): secrets "apps-bauxite-viu-tls" not found
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl describe ingress fanout-ingress-voyager -n xyz-product
Name:             fanout-ingress-voyager
Namespace:        xyz-product
Address:
Default backend:  default-http-backend:80 (10.0.0.8:8080)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *
        /user-reg/create/*   prod-user-reg-create-app:8081 (<none>)
Annotations:
  cert-manager.io/acme-challenge-type:               http01
  cert-manager.io/cluster-issuer:                    letsencrypt-staging-issuer
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/acme-challenge-type":"http01","cert-manager.io/cluster-issuer":"letsencrypt-staging-issuer","kubernetes.io/ingress.class":"voyager"},"name":"fanout-ingress-voyager","namespace":"xyz-product"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"prod-user-reg-create-app","servicePort":8081},"path":"/user-reg/create/*"}]}}]}}

  kubernetes.io/ingress.class:  voyager
Events:
  Type    Reason                         Age   From              Message
  ----    ------                         ----  ----              -------
  Normal  ConfigMapReconcileSuccessful   36s   voyager-operator  Successfully created ConfigMap voyager-fanout-ingress-voyager
  Normal  RBACSuccessful                 36s   voyager-operator  Successfully created ServiceAccount voyager-fanout-ingress-voyager
  Normal  RBACSuccessful                 36s   voyager-operator  Successfully created Role voyager-fanout-ingress-voyager
  Normal  RBACSuccessful                 36s   voyager-operator  Successfully created RoleBinding voyager-fanout-ingress-voyager
  Normal  DeploymentReconcileSuccessful  36s   voyager-operator  Successfully created HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  ServiceReconcileSuccessful     36s   voyager-operator  Successfully created LoadBalancer Service voyager-fanout-ingress-voyager

```

**Comment by git4suvendu** [comment]
So, again I have have created ingress with tls bit getting this error. 


 : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/183116 (24) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/183116 (24) : Fatal errors found in configuration.
 exit status 1
  Warning  TLSMountFailed                 7s  haproxy-controller  secret "apps-bauxite-viu-tls" not found
  Warning  TLSMountFailed                 7s  haproxy-controller  secret "apps-bauxite-viu-tls" not found
  Normal   ConfigMapReconcileSuccessful   7s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Normal   CreateCertificate              7s  cert-manager        Successfully created Certificate "apps-bauxite-viu-tls"
  Normal   DeploymentReconcileSuccessful  7s  voyager-operator    Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                 7s  haproxy-controller  secret "apps-bauxite-viu-tls" not found
  Normal   StatsServiceDeleteSuccessful   7s  voyager-operator    Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Warning  TLSMountFailed                 7s  haproxy-controller  secret "apps-bauxite-viu-tls" not found
  Warning  TLSMountFailed                 7s  haproxy-controller  secret "apps-bauxite-viu-tls" not found
  Warning  TLSMountFailed                 7s  haproxy-controller  secret "apps-bauxite-viu-tls" not found
  Normal   ServiceReconcileSuccessful     7s  voyager-operator    Successfully patched LoadBalancer Service voyager-fanout-ingress-voyager
  Warning  BackendInvalid                 5s  voyager-operator    can't resolve backend for spec.rules[0].http.paths[0], reason: endpoint not found
  Normal   ConfigMapReconcileSuccessful   5s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                 5s  haproxy-controller  haproxy-check failed, reason: [ALERT] 331/183118 (25) : parsing [/etc/haproxy/haproxy.cfg:50] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/183118 (25) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/183118 (25) : Fatal errors found in configuration.
 exit status 1
  Normal   DeploymentReconcileSuccessful  5s  voyager-operator    Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal   StatsServiceDeleteSuccessful   5s  voyager-operator    Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
  Normal   ConfigMapReconcileSuccessful   3s  voyager-operator    Successfully patched ConfigMap voyager-fanout-ingress-voyager
  Warning  TLSMountFailed                 3s  haproxy-controller  haproxy-check failed, reason: [ALERT] 331/183120 (26) : parsing [/etc/haproxy/haproxy.cfg:50] : 'bind *:443' : unable to load SSL certificate from PEM file '/etc/ssl/private/haproxy/tls/apps-bauxite-viu-tls.pem'.
[ALERT] 331/183120 (26) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 331/183120 (26) : Fatal errors found in configuration.
 exit status 1
  Normal  DeploymentReconcileSuccessful  3s  voyager-operator  Successfully patched HAProxy Deployment voyager-fanout-ingress-voyager
  Normal  StatsServiceDeleteSuccessful   3s  voyager-operator  Successfully deleted stats Service voyager-fanout-ingress-voyager-stats
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$

**Comment by tamalsaha** [comment]
Why did you delete the ingress?

**Comment by tamalsaha** [comment]
`kubectl get certificate -n xyz-product` ?

**Comment by git4suvendu** [comment]
I wanted to do it freshly. 
Step1: Delete Ingress and Secret
Step2: Deploy Ingress without TLS. (At this stage secret should create as you mentioned earlier). However, it didn't create the secret.
Step3: Deploy the same Ingress with TLS. (At this stage secret is getting created but not binding with HAProxy.)

Please advise.

**Comment by git4suvendu** [comment]
```
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl get certificate -n xyz-product
NAME                   READY   SECRET                 AGE
apps-bauxite-viu-tls   False   apps-bauxite-viu-tls   13m
```

**Comment by tamalsaha** [comment]
Your certificate is not ready. Why? Do you have the secret `apps-bauxite-viu-tls` ?

**Comment by git4suvendu** [comment]
```
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl get secret apps-bauxite-viu-tls -n xyz-product
NAME                   TYPE                DATA   AGE
apps-bauxite-viu-tls   kubernetes.io/tls   3      16m
```

**Comment by git4suvendu** [comment]
```
    API Version:           extensions/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Ingress
    Name:                  fanout-ingress-voyager
    UID:                   5bc92753-120c-11ea-a99b-42010a9a008d
  Resource Version:        124182
  Self Link:               /apis/cert-manager.io/v1alpha2/namespaces/xyz-product/certificates/apps-bauxite-viu-tls
  UID:                     43763f14-120d-11ea-a99b-42010a9a008d
Spec:
  Dns Names:
    apps.bauxite-viu.co.uk
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt-staging-issuer
  Secret Name:  apps-bauxite-viu-tls
Status:
  Conditions:
    Last Transition Time:  2019-11-28T18:31:16Z
    Message:               Waiting for CertificateRequest "apps-bauxite-viu-tls-345221582" to complete
    Reason:                InProgress
    Status:                False
    Type:                  Ready
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  GeneratedKey  15m   cert-manager  Generated a new private key
  Normal  Requested     15m   cert-manager  Created new CertificateRequest resource "apps-bauxite-viu-tls-345221582"
```

**Comment by tamalsaha** [comment]
`kubectl get deployment voyager-fanout-ingress-voyager -n xyz-product`?

**Comment by tamalsaha** [comment]
I am still seeing `can't resolve backend for spec.rules[0].http.paths[0], reason: endpoint not found` . Do you have the svc?

**Comment by git4suvendu** [comment]
This what I have deployed after deleting the ingress and secret.
```

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress-voyager
  namespace: xyz-product
  annotations:
    kubernetes.io/ingress.class: voyager
    cert-manager.io/cluster-issuer: "letsencrypt-staging-issuer"
    cert-manager.io/acme-challenge-type: http01
spec:
  rules:
  - host: apps.bauxite-viu.co.uk
    http:
      paths:
      - path: /user-reg/create/*
        backend:
          serviceName: prod-user-reg-create-app
          servicePort: 8081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress-voyager
  namespace: xyz-product
  annotations:
    kubernetes.io/ingress.class: voyager
    cert-manager.io/cluster-issuer: "letsencrypt-staging-issuer"
    cert-manager.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
        - apps.bauxite-viu.co.uk
      secretName: apps-bauxite-viu-tls
  rules:
  - host: apps.bauxite-viu.co.uk
    http:
      paths:
      - path: /user-reg/create/*
        backend:
          serviceName: prod-user-reg-create-app
          servicePort: 8081
---
```

**Comment by git4suvendu** [comment]
Log file atatched
[logfile.log](https://github.com/appscode/voyager/files/3902840/logfile.log)

**Comment by tamalsaha** [comment]
can you `kubectl describe secret apps-bauxite-viu-tls -n xyz-product` ?

**Comment by tamalsaha** [comment]
and 

`kubectl get deployment voyager-fanout-ingress-voyager -n xyz-product` ?

**Comment by git4suvendu** [comment]
```
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl describe secret apps-bauxite-viu-tls -n xyz-product
Name:         apps-bauxite-viu-tls
Namespace:    xyz-product
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: apps-bauxite-viu-tls
              cert-manager.io/issuer-kind: ClusterIssuer
              cert-manager.io/issuer-name: letsencrypt-staging-issuer

Type:  kubernetes.io/tls

Data
====
tls.key:  1679 bytes
ca.crt:   0 bytes
tls.crt:  0 bytes
```
```
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$ kubectl get deployment voyager-fanout-ingress-voyager -n xyz-product
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
voyager-fanout-ingress-voyager   1/1     1            1           10m
suvendu_mandal@cloudshell:~ (optimal-cogency-258718)$


```

**Comment by tamalsaha** [comment]
`tls.key:  1679 bytes
ca.crt:   0 bytes
tls.crt:  0 bytes`

Why the tls.crt is 0 bytes?

**Comment by git4suvendu** [comment]
I don't know. It should automatically create right? Or I need to pass cert?

**Comment by tamalsaha** [comment]
What version of cert manager are you using? What version of voyager are you using?

**Comment by git4suvendu** [comment]
This is my cluster issuer. :(

```
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-issuer
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: suvendu.mandal@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: staging-issuer-account-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            name: fanout-ingress-voyager #Ingress name.
```
