### ISSUE TITLE
voyager helm install failed for version v12.0.0-rc.2

### ISSUE THREAD

**Issue by nrvmodi** [voyagermesh/voyager#1501]
Hello,
I had run below command to run voyager ingress in my aws eks cluster.

`helm install voyager-operator appscode/voyager --version v12.0.0-rc.2`

voyager-operator run successfully but when i tried to run ingress-resource.yaml file. 
It gives below error for ingress-haproxy pod.

`voyager-ray-ingress-7b6bc59957-z5zg9   0/1     ImagePullBackOff`

When I describe the above pod in k8s.

```
Name:         voyager-ray-ingress-7b6bc59957-z5zg9
Namespace:    ray-prod
Priority:     0
Node:         ip-10-0-1-246.ap-south-1.compute.internal/10.0.1.246
Start Time:   Thu, 07 May 2020 16:27:14 +0530
Labels:       origin=voyager
              origin-api-group=voyager.appscode.com
              origin-name=ray-ingress
              pod-template-hash=7b6bc59957
Annotations:  ingress.appscode.com/last-applied-annotation-keys: 
              kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           10.0.1.238
IPs:
  IP:           10.0.1.238
Controlled By:  ReplicaSet/voyager-ray-ingress-7b6bc59957
Containers:
  haproxy:
    Container ID:  
    Image:         appscode/haproxy:haproxy
    Image ID:      
    Port:          80/TCP
    Host Port:     0/TCP
    Args:
      --enable-analytics=true
      --burst=1000000
      --cloud-provider=
      --ingress-api-version=voyager.appscode.com/v1beta1
      --ingress-name=ray-ingress
      --qps=1e+06
      --logtostderr=false
      --alsologtostderr=false
      --v=3
      --stderrthreshold=0
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      APPSCODE_ANALYTICS_CLIENT_ID:  d3ee882e19e76cfd29aa90187264b901
    Mounts:
      /etc/ssl/private/haproxy from voyager-certdir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from voyager-ray-ingress-token-xfktb (ro)

```
```
Events:
  Type     Reason     Age                  From                                                Message
  ----     ------     ----                 ----                                                -------
  Normal   Scheduled  14m                  default-scheduler                                   Successfully assigned ray-prod/voyager-ray-ingress-7b6bc59957-z5zg9 to ip-10-0-1-246.ap-south-1.compute.internal
  Normal   Pulling    12m (x4 over 14m)    kubelet, ip-10-0-1-246.ap-south-1.compute.internal  Pulling image "appscode/haproxy:haproxy"
  Warning  Failed     12m (x4 over 14m)    kubelet, ip-10-0-1-246.ap-south-1.compute.internal  Failed to pull image "appscode/haproxy:haproxy": rpc error: code = Unknown desc = Error response from daemon: manifest for appscode/haproxy:haproxy not found
  Warning  Failed     12m (x4 over 14m)    kubelet, ip-10-0-1-246.ap-south-1.compute.internal  Error: ErrImagePull
  Normal   BackOff    12m (x6 over 14m)    kubelet, ip-10-0-1-246.ap-south-1.compute.internal  Back-off pulling image "appscode/haproxy:haproxy"
  Warning  Failed     4m9s (x42 over 14m)  kubelet, ip-10-0-1-246.ap-south-1.compute.internal  Error: ImagePullBackOff

```

I observed that Image must be `appscode/haproxy:1.9.15-v12.0.0-rc.2-alpine` but it is `appscode/haproxy:haproxy`. 

My deployment yaml is like below and it contains `--haproxy-image-tag=1.9.15-v12.0.0-rc.2-alpine`
but somehow that tag is not implemented in this version. 

```

# Source: voyager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyager-operator
  namespace: ray-prod
  labels:
    helm.sh/chart: voyager-v12.0.0-rc.2
    app.kubernetes.io/name: voyager
    app.kubernetes.io/instance: voyager-operator
    app.kubernetes.io/version: "v12.0.0-rc.2"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voyager
      app.kubernetes.io/instance: voyager-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voyager
        app.kubernetes.io/instance: voyager-operator
      annotations:
        checksum/apiregistration.yaml: 66ec163a6cf0ffcfcfa5b8e5add97fd476e72353864d29393e5add0184a44f39
    spec:
      serviceAccountName: voyager-operator
      containers:
      - name: voyager
        securityContext:
          {}
        image: appscode/voyager:v12.0.0-rc.2
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --cloud-provider=
        - --cloud-config=
        - --v=3
        - --ingress-class=
        - --operator-service=voyager-operator
        - --docker-registry=appscode
        - --haproxy-image-tag=1.9.15-v12.0.0-rc.2-alpine
        - --haproxy-image-repository=haproxy
        - --exporter-image-tag=v12.0.0-rc.2
        - --exporter-image-repository=voyager
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-validating-webhook=true
        - --bypass-validating-webhook-xray=false
        - --use-kubeapiserver-fqdn-for-aks=true
        - --enable-analytics=true
        ports:
        - containerPort: 8443
        - containerPort: 56791
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: voyager-operator-apiserver-cert
      securityContext:
        fsGroup: 65535
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        beta.kubernetes.io/os: linux

```
How to solve this ImagePull issue for pod?
