### ISSUE TITLE
Voyager Ingress with type Internal not working

### ISSUE THREAD

**Issue by nrvmodi** [voyagermesh/voyager#1502]
Hello, 

I have installed voyager using below command. 
`helm install voyager-operator appscode/voyager --version v12.0.0-rc.0 --set cloudProvider=aws`

Issue : host based routing not working

I had applied below ingress config.

```
apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.appscode.com/type: Internal
  name: ray-ingress
  namespace: ray-prod
spec:       
  rules:
  - host: crate.web.internal
    http:
      paths:
        - backend:
            serviceName: crate-internal-service
            servicePort: 4200   
```

`kubectl describe service  voyager-ray-ingress`

```
Name:              voyager-ray-ingress
Namespace:         ray-prod
Labels:            origin=voyager
                   origin-api-group=voyager.appscode.com
                   origin-name=ray-ingress
Annotations:       ingress.appscode.com/last-applied-annotation-keys: 
                   ingress.appscode.com/origin-api-schema: voyager.appscode.com/v1beta1
                   ingress.appscode.com/origin-name: ray-ingress
Selector:          origin-api-group=voyager.appscode.com,origin-name=ray-ingress,origin=voyager
Type:              ClusterIP
IP:                172.20.89.211
Port:              tcp-4200  4200/TCP
TargetPort:        4200/TCP
Endpoints:         10.0.3.43:4200
Port:              tcp-80  80/TCP
TargetPort:        80/TCP
Endpoints:         10.0.3.43:80
Session Affinity:  None
Events:            <none>

```
Yoy can see in config  i have used  internal type. like `ingress.appscode.com/type: Internal`

When I used default type `Loadbalancer` then I can telnet to 80 port 
using `telnet <external_LB_IP> 80`

but when I  use `Internal`, it is not working. I had configured INTERNAL_lB infront of Ingress.
and try to connect 
using `telnet <INTERNAL_LB_IP> 80`

Voyager ingress create classic load balancer.

Does Ingress support internal nlb on aws? if yes can you guid me how to configure that.
