### ISSUE TITLE
Voyager unable to update haproxy.cfg - must have at most 1048576 characters

### ISSUE THREAD

**Issue by ronald** [voyagermesh/voyager#1553]
When updating ConfigMap with haproxy.cfg Voyager Operator reports 

`Failed to process key default/ingress. Reason: ConfigMap "voyager-ingress" is invalid: []: Too long: must have at most 1048576 characters`

I'll check if [Custom Templates](https://voyagermesh.com/docs/v11.0.1/guides/ingress/configuration/custom-templates/) can help reduce haproxy.cfg size.

Is there any other workaround?

Thank you

**Comment by ronald** [comment]
We have 1.460 configured backends in ingress - 99% look like this:
```yaml
  - host: example.com
    http:
      paths:
      - backend:
          headerRules:
          - X-Forwarded-Host %[req.hdr(Host)]
          - X-Forwarded-Port %[dst_port]
          - X-Forwarded-Proto https if { ssl_fc }
          serviceName: our-service
          servicePort: 80
        path: /
```

Voyager generated haproxy.cfg with 2.917 backends - 99 % like this:
```
backend our-service.default:80-3108123b8583519de78f980b53f3d5c9                                                                                                                                                    
        http-request set-header X-Forwarded-Host %[req.hdr(Host)]                                                                                                                                                  
        http-request set-header X-Forwarded-Port %[dst_port]                                                                                                                                                       
        http-request set-header X-Forwarded-Proto https if { ssl_fc }                                                                                                                                              
        server pod-our-service-deployment-7d8b65d887-kfrpw 10.12.22.52:80     
```
